apiVersion: installer.kubesphere.io/v1alpha1
kind: ClusterConfiguration
metadata:
  name: ks-installer
  namespace: kubesphere-system
  labels:
    version: v3.3.1
spec:
  persistence:
    storageClass: "scanpro-local-storage" # Use the storage class created for ScanPro
  authentication:
    jwtSecret: ""
  local_registry: ""
  etcd:
    monitoring: true
    endpointIps: localhost
    port: 2379
    tlsEnable: true
  common:
    redis:
      enabled: true
    redisVolumSize: 2Gi
    openldap:
      enabled: true
      volumeSize: 2Gi
    minioVolumeSize: 20Gi
    monitoring:
      # type: prometheus
      endpoint: http://prometheus-operated.kubesphere-monitoring-system.svc:9090
      GPUMonitoring:
        enabled: false
    es: # Storage backend for logging, events and auditing
      # elasticsearchMasterReplicas: 1
      # elasticsearchDataReplicas: 1
      elasticsearchMasterVolumeSize: 4Gi
      elasticsearchDataVolumeSize: 20Gi
      logMaxAge: 7
      elkPrefix: logstash
      basicAuth:
        enabled: false
        username: ""
        password: ""
      externalElasticsearchUrl: ""
      externalElasticsearchPort: ""
  console:
    enableMultiLogin: true # Enable/disable multiple concurrent logins
    port: 30880
  alerting: # (CPU: 0.1 Core, Memory: 100 MiB)
    enabled: true
    # thanosruler:
    #   replicas: 1
    #   resources: {}
  auditing: # Auditing records user operations on the platform
    enabled: true
  devops:
    enabled: false
    jenkinsMemoryLim: 2Gi
    jenkinsMemoryReq: 1500Mi
    jenkinsVolumeSize: 8Gi
    jenkinsJavaOpts_Xms: 512m
    jenkinsJavaOpts_Xmx: 512m
    jenkinsJavaOpts_MaxRAM: 2g
  events:
    enabled: true
    ruler:
      enabled: true
      replicas: 2
  logging:
    enabled: true
    containerruntime: containerd
    logsidecar:
      enabled: true
      replicas: 2
  metrics_server:
    enabled: true
  monitoring:
    storageClass: scanpro-local-storage
    prometheusMemoryRequest: 500Mi
    prometheusVolumeSize: 20Gi
  multicluster:
    clusterRole: none
  network:
    networkpolicy:
      enabled: false
    ippool:
      type: none
    topology:
      type: none
  openpitrix:
    store:
      enabled: true
  servicemesh: # (0.3 Core, 300 MiB)
    enabled: false
