apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scanpro-uploads-pvc
  namespace: scanpro
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: scanpro-local-storage
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scanpro-conversions-pvc
  namespace: scanpro
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: scanpro-local-storage
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scanpro-compressions-pvc
  namespace: scanpro
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: scanpro-local-storage
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scanpro-ocr-pvc
  namespace: scanpro
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: scanpro-local-storage
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scanpro-temp-pvc
  namespace: scanpro
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: scanpro-local-storage
  resources:
    requests:
      storage: 10Gi
