apiVersion: apps/v1
kind: Deployment
metadata:
  name: scanpro-frontend
  namespace: scanpro
  labels:
    app: scanpro
    component: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: scanpro
      component: frontend
  template:
    metadata:
      labels:
        app: scanpro
        component: frontend
    spec:
      containers:
        - name: frontend
          image: your-registry/scanpro:latest
          imagePullPolicy: Always
          command: ["npm", "run", "start"]
          ports:
            - containerPort: 3000
              name: http
          envFrom:
            - configMapRef:
                name: scanpro-config
            - secretRef:
                name: scanpro-secrets
                optional: true
          env:
            - name: NEXTAUTH_URL
              valueFrom:
                configMapKeyRef:
                  name: scanpro-config
                  key: NEXT_PUBLIC_APP_URL
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "300m"
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: scanpro-frontend
  namespace: scanpro
  labels:
    app: scanpro
    component: frontend
spec:
  ports:
    - port: 80
      targetPort: 3000
      name: http
  selector:
    app: scanpro
    component: frontend
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: scanpro-frontend-hpa
  namespace: scanpro
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: scanpro-frontend
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
